### ISSUE TITLE
Difference to other projects

### ISSUE THREAD

**Issue by malteos** [OpenLegalTech/django-legal-advice-builder#22]
Hi,

great work! How does your project compare to other projects like Docassemble? https://docassemble.org/

Best,
Malte

**Comment by MagdaN** [comment]
Hi @malteos,

thank you, the main difference is, that I implemented an User Interface to create Interviews, Decision Trees and Document Templates and there is no need to know and use YAML, Markdown, and Python.

Cheers
Magda
